name: Update VPN Subscription (SUB_9PB)

on:
  schedule:
    - cron: "0 */3 * * *" # Runs every 3 hours
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'If true, only generate YAML locally without pushing'
        required: false
        default: 'false'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install axios js-yaml

      - name: Run update script
        id: generate_yaml
        run: |
          node <<'EOF'
          const axios = require('axios');
          const yaml = require('js-yaml');
          const fs = require('fs');
          const { URL } = require('url');
          const path = require('path');

          const SUB_URL = process.env.SUB_9PB;
          const GH_TOKEN = process.env.GH_TOKEN;
          const GITHUB_FILE = "9PB";
          const dryRun = process.env.DRY_RUN === "true";

          function b64decode(s) {
            if (s.length % 4) s += "=".repeat(4 - (s.length % 4));
            return Buffer.from(s, 'base64').toString('utf8');
          }

          function parseVmess(link) { /* same as before */ }
          function parseVless(link) { /* same as before */ }
          function parseTrojan(link) { /* same as before */ }
          function parseHysteria2(link) { /* same as before */ }
          function parseAnytls(link) { /* same as before */ }

          async function main() {
            const res = await axios.get(SUB_URL, { responseType: 'text' });

            let lines = b64decode(res.data.trim())
              .split(/\r?\n/)
              .filter(Boolean)
              .slice(2); // remove first 2 info lines

            const proxies = [];
            for (const line of lines) {
              if (line.startsWith("vmess://")) proxies.push(parseVmess(line));
              else if (line.startsWith("vless://")) proxies.push(parseVless(line));
              else if (line.startsWith("trojan://")) proxies.push(parseTrojan(line));
              else if (line.startsWith("hysteria2://")) proxies.push(parseHysteria2(line));
              else if (line.startsWith("anytls://")) proxies.push(parseAnytls(line));
            }

            console.log(`🔹 Total proxies parsed: ${proxies.length}`);
            console.log("Proxy names:", proxies.map(p => p.name).join(", "));

            const clashConfig = {
              proxies,
              "proxy-groups": [
                {
                  name: "Auto",
                  type: "url-test",
                  proxies: proxies.map(p => p.name),
                  url: "http://www.gstatic.com/generate_204",
                  interval: 300
                }
              ],
              rules: ["MATCH,Auto"]
            };

            const yamlData = yaml.dump(clashConfig, { noRefs: true, forceQuotes: false, lineWidth: 120 });

            fs.writeFileSync(GITHUB_FILE, yamlData, "utf8");
            fs.writeFileSync(path.join(process.cwd(), "9PB.yml"), yamlData, "utf8");

            if (!dryRun) {
              try {
                // Force commit by always adding timestamp in commit message
                await axios.put(
                  `https://api.github.com/repos/Vanic24/VPN/contents/${GITHUB_FILE}`,
                  {
                    message: `Auto update Clash YAML 9PB at ${new Date().toISOString()}`,
                    content: Buffer.from(yamlData).toString('base64')
                  },
                  { headers: { Authorization: `token ${GH_TOKEN}` } }
                );
                console.log("✅ GitHub updated successfully (forced commit)");
              } catch (e) {
                console.error("⚠️ Failed to update GitHub:", e.message);
              }
            } else {
              console.log("⚠️ Dry run enabled — YAML generated but not pushed.");
            }
          }

          main().catch(e => {
            console.error("❌ Error:", e);
            process.exit(1);
          });
          EOF
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SUB_9PB: ${{ secrets.SUB_9PB }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}

      - name: Upload Clash YAML artifact
        uses: actions/upload-artifact@v4
        with:
          name: 9PB
          path: 9PB.yml

      - name: Delete old artifacts (keep latest 2)
        run: |
          echo "🔍 Checking for old artifacts..."
          artifact_ids=$(gh api repos/${{ github.repository }}/actions/artifacts \
            --jq '.artifacts[] | select(.name=="9PB") | .id')

          keep_ids=$(echo "$artifact_ids" | head -n 2)
          delete_ids=$(echo "$artifact_ids" | tail -n +3)

          if [ -z "$delete_ids" ]; then
            echo "✅ No old artifacts to delete."
          else
            for id in $delete_ids; do
              gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$id
              echo "🗑 Deleted old artifact $id"
            done
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
